// SPDX-License-Identifier: EUPL-1.2
/**
 * Resource-monitor degrade shim for `mach build`.
 *
 * mozbuild's build resource monitor calls `psutil.virtual_memory()` at
 * startup (`start_resource_recording`). On some hosts (psutil vs Darwin 27)
 * that raises `RuntimeError: host_statistics64(HOST_VM_INFO64) syscall
 * failed`, which aborts `mach build` / `mach build faster` before any work
 * happens — so a raw `./mach build faster` dies while the build never
 * reaches the compiler. The suite-specific test commands sidestep the
 * monitor entirely, but the build commands have no such escape.
 *
 * FireForge writes a tiny `sitecustomize.py` and points the mach
 * subprocess's `PYTHONPATH` at it. Python imports `sitecustomize` at
 * interpreter startup (before mach runs), so the shim wraps
 * `psutil.virtual_memory` / `swap_memory` to downgrade the host syscall
 * failure into a non-fatal `UserWarning` and return a zeroed reading. The
 * build then proceeds regardless of which mach entry point spawned it. When
 * psutil works normally the wrapper is a transparent pass-through.
 */

import { tmpdir } from 'node:os';
import { delimiter, join } from 'node:path';

import { ensureDir, writeText } from '../utils/fs.js';

/** Directory name (under the OS temp dir) holding the generated shim. */
const RESOURCE_SHIM_DIRNAME = 'fireforge-mach-resource-shim';

/**
 * `sitecustomize.py` body. Defensive: a missing/broken psutil leaves mach
 * untouched, and the wrapper only intercepts the failure path.
 */
const SITECUSTOMIZE_SOURCE = `# Generated by FireForge — do not edit.
# Degrades a broken host resource monitor (psutil vs Darwin) from a fatal
# RuntimeError in start_resource_recording into a non-fatal warning, so
# \`mach build\` does not abort before the build runs. Loaded via PYTHONPATH
# so it patches psutil before mach's resource monitor starts.
import warnings

try:
    import psutil
except Exception:
    psutil = None

if psutil is not None:
    class _DegradedReading(object):
        total = available = used = free = active = inactive = wired = 0
        percent = 0.0

        def __getattr__(self, _name):
            return 0

    def _guard(orig):
        def wrapper(*args, **kwargs):
            try:
                return orig(*args, **kwargs)
            except Exception as exc:  # noqa: BLE001
                warnings.warn(
                    "FireForge: host resource monitor degraded (%s); build continues." % exc
                )
                return _DegradedReading()

        return wrapper

    for _name in ("virtual_memory", "swap_memory"):
        _orig = getattr(psutil, _name, None)
        if _orig is not None:
            setattr(psutil, _name, _guard(_orig))
`;

/**
 * Writes the `sitecustomize.py` degrade shim into a stable FireForge-owned
 * temp directory and returns that directory. Idempotent — overwriting the
 * file each call keeps it in sync with this source if FireForge upgrades.
 */
async function ensureMachResourceShim(): Promise<string> {
  const dir = join(tmpdir(), RESOURCE_SHIM_DIRNAME);
  await ensureDir(dir);
  await writeText(join(dir, 'sitecustomize.py'), SITECUSTOMIZE_SOURCE);
  return dir;
}

/**
 * Builds the `env` overlay (merged over `process.env` by the exec layer)
 * that prepends the shim directory to `PYTHONPATH`, so the mach subprocess
 * imports the degrade `sitecustomize` without clobbering an existing
 * `PYTHONPATH`.
 */
function machResourceShimEnv(
  shimDir: string,
  baseEnv: NodeJS.ProcessEnv = process.env
): Record<string, string> {
  const existing = baseEnv['PYTHONPATH'];
  return { PYTHONPATH: existing ? `${shimDir}${delimiter}${existing}` : shimDir };
}

/** Ensures the shim exists and returns the mach `env` overlay that enables it. */
export async function resolveMachBuildEnv(): Promise<Record<string, string>> {
  return machResourceShimEnv(await ensureMachResourceShim());
}
