// SPDX-License-Identifier: EUPL-1.2
/**
 * Resource-monitor degrade guard for mach dispatches.
 *
 * mozbuild's build resource monitor calls `psutil.virtual_memory()` at
 * startup (`start_resource_recording`) and again later from
 * `mozbuild.base._run_make`. On some hosts (psutil vs Darwin 27) those
 * raise `RuntimeError: host_statistics64(HOST_VM_INFO64) syscall failed`,
 * and a `SystemResourceMonitor.__init__` that fails partway leaves an
 * instance without `poll_interval`, so later polling dies with
 * `AttributeError: ... poll_interval`. Any of these aborts `mach build` /
 * `mach build faster` before the compiler ever runs.
 *
 * 0.33.0 injected a `sitecustomize.py` via the mach subprocess PYTHONPATH.
 * Field report (0.34.0 cycle): mach re-execs itself into its private
 * virtualenv and drops PYTHONPATH, so the env-var route never loads and
 * the crash family escaped on every protected entry point. FireForge now
 * owns the guard in-process on its mach dispatches by installing a
 * `fireforge_mach_guard.pth` + module pair directly into every discovered
 * mach virtualenv site-packages directory: `.pth` files execute at
 * interpreter startup from the venv's own site-packages, which survives
 * the re-exec. The PYTHONPATH `sitecustomize.py` is retained only as a
 * belt-and-suspenders for the pre-venv bootstrap phase (first build, no
 * `_virtualenvs` on disk yet).
 *
 * The guard itself covers the whole crash family:
 *  - wraps `psutil.virtual_memory` / `swap_memory` / `cpu_percent` /
 *    `cpu_times` / `disk_io_counters` module-wide, so every call site —
 *    including the direct `psutil.virtual_memory()` in
 *    `mozbuild.base._run_make` — degrades to a `UserWarning` and a zeroed
 *    reading instead of aborting. Downstream report (0.34.0 cycle):
 *    mozsystemmonitor subscripts (`_build_meta` does
 *    `psutil.virtual_memory()[0]`) and iterates/unpacks the reading, so the
 *    zeroed fallback is a full namedtuple duck type — a zeroed instance of
 *    psutil's own result namedtuple where resolvable without touching the
 *    failing syscall, else `_DegradedReading` (subscriptable, iterable, with
 *    `len()`, `_fields`, `_asdict()`); `cpu_percent` degrades to `0.0`
 *    because callers do arithmetic on it;
 *  - guards `SystemResourceMonitor` CONSTRUCTION via an import hook:
 *    `poll_interval` is pre-populated before the real `__init__` runs, a
 *    failing `__init__` marks the instance degraded instead of raising,
 *    and every monitor method no-ops on a degraded instance — so a
 *    partially-constructed monitor can never surface the
 *    `AttributeError: poll_interval` variant.
 */

import { readdir } from 'node:fs/promises';
import { homedir, tmpdir } from 'node:os';
import { delimiter, join } from 'node:path';

import { toError } from '../utils/errors.js';
import { ensureDir, pathExists, writeText } from '../utils/fs.js';
import { verbose } from '../utils/logger.js';

/** Directory name (under the OS temp dir) holding the PYTHONPATH fallback. */
const RESOURCE_SHIM_DIRNAME = 'fireforge-mach-resource-shim';

/** Basename (sans extension) of the in-venv guard module. */
const GUARD_MODULE_NAME = 'fireforge_mach_guard';

/**
 * Python guard body, importable both as the in-venv `fireforge_mach_guard`
 * module (loaded by the sibling `.pth` at interpreter startup) and as the
 * PYTHONPATH `sitecustomize` fallback. Defensive throughout: a missing or
 * broken psutil/mozsystemmonitor leaves mach untouched, and every wrapper
 * only intercepts the failure path. Exported for the Python-executing
 * regression test (mach-resource-shim.python.test.ts), which asserts the
 * degraded readings' runtime behavior rather than string-matching the source.
 */
export const GUARD_PYTHON_SOURCE = `# Generated by FireForge - do not edit.
# Degrades the broken host resource monitor family (psutil vs Darwin) from
# fatal startup errors into non-fatal warnings, so mach builds and tests
# proceed. Installed into the mach virtualenv site-packages via a .pth file
# (survives mach's venv re-exec, which drops PYTHONPATH).
import builtins
import sys
import warnings


def _fireforge_degraded_notice(exc):
    warnings.warn(
        "FireForge: host resource monitor degraded (%s); continuing without resource monitoring." % exc
    )


class _DegradedReading(object):
    # Duck type of psutil's namedtuple results (svmem field order):
    # mozsystemmonitor subscripts, iterates, and unpacks readings, so the
    # degraded fallback must survive r[0], list(r), len(r), r._fields and
    # r._asdict(), not just attribute access.
    _fields = ("total", "available", "percent", "used", "free", "active", "inactive", "wired")
    total = available = used = free = active = inactive = wired = 0
    percent = 0.0

    def __getattr__(self, _name):
        return 0

    def _values(self):
        return tuple(getattr(self, _field) for _field in self._fields)

    def __getitem__(self, index):
        return self._values()[index]

    def __iter__(self):
        return iter(self._values())

    def __len__(self):
        return len(self._fields)

    def _asdict(self):
        return dict(zip(self._fields, self._values()))


# psutil result namedtuple per wrapped function, resolvable via getattr from
# the platform module / _common without invoking the failing syscall.
_PSUTIL_RESULT_CLASSES = {
    "virtual_memory": "svmem",
    "swap_memory": "sswap",
    "cpu_times": "scputimes",
    "disk_io_counters": "sdiskio",
}


def _degraded_result_factory(psutil, name):
    # cpu_percent returns a plain float callers do arithmetic on.
    if name == "cpu_percent":
        return lambda: 0.0
    _cls_name = _PSUTIL_RESULT_CLASSES.get(name)
    if _cls_name is not None:
        for _mod in (getattr(psutil, "_psplatform", None), getattr(psutil, "_common", None)):
            _cls = getattr(_mod, _cls_name, None) if _mod is not None else None
            _fields = getattr(_cls, "_fields", None)
            if _cls is not None and _fields:
                return lambda _cls=_cls, _n=len(_fields): _cls(*([0] * _n))
    return _DegradedReading


def _guard_psutil():
    try:
        import psutil
    except Exception:
        return

    def _wrap(orig, fallback):
        def wrapper(*args, **kwargs):
            try:
                return orig(*args, **kwargs)
            except Exception as exc:  # noqa: BLE001
                _fireforge_degraded_notice(exc)
                try:
                    return fallback()
                except Exception:  # noqa: BLE001
                    return _DegradedReading()

        return wrapper

    for _name in ("virtual_memory", "swap_memory", "cpu_percent", "cpu_times", "disk_io_counters"):
        _orig = getattr(psutil, _name, None)
        if _orig is not None and not getattr(_orig, "_fireforge_guarded", False):
            try:
                _fallback = _degraded_result_factory(psutil, _name)
            except Exception:  # noqa: BLE001
                _fallback = _DegradedReading
            _wrapped = _wrap(_orig, _fallback)
            _wrapped._fireforge_guarded = True
            setattr(psutil, _name, _wrapped)


_MONITOR_METHOD_NAMES = (
    "start",
    "stop",
    "record_event",
    "record_marker",
    "begin_phase",
    "finish_phase",
    "aggregate_cpu_percent",
    "aggregate_cpu_times",
    "aggregate_io",
    "min_memory_available",
    "as_dict",
)


def _patch_monitor_class(cls):
    if cls is None or getattr(cls, "_fireforge_guarded", False):
        return
    orig_init = cls.__init__

    def guarded_init(self, *args, **kwargs):
        # Pre-populate the attributes a partially-constructed instance is
        # later polled for, so a failing __init__ can never surface
        # AttributeError: poll_interval.
        self.poll_interval = kwargs.get("poll_interval") or 1.0
        self._fireforge_degraded = False
        try:
            orig_init(self, *args, **kwargs)
        except Exception as exc:  # noqa: BLE001
            self._fireforge_degraded = True
            _fireforge_degraded_notice(exc)

    cls.__init__ = guarded_init

    def _wrap_method(orig):
        def wrapper(self, *args, **kwargs):
            if getattr(self, "_fireforge_degraded", False):
                return None
            try:
                return orig(self, *args, **kwargs)
            except Exception as exc:  # noqa: BLE001
                self._fireforge_degraded = True
                _fireforge_degraded_notice(exc)
                return None

        return wrapper

    for _name in _MONITOR_METHOD_NAMES:
        _orig = getattr(cls, _name, None)
        if _orig is not None:
            setattr(cls, _name, _wrap_method(_orig))
    cls._fireforge_guarded = True


_MONITOR_MODULES = ("mozsystemmonitor.resourcemonitor", "mozbuild.resources")


def _patch_loaded_monitor_modules():
    for _mod_name in _MONITOR_MODULES:
        _mod = sys.modules.get(_mod_name)
        if _mod is not None:
            try:
                _patch_monitor_class(getattr(_mod, "SystemResourceMonitor", None))
            except Exception:  # noqa: BLE001
                pass


def _install_import_hook():
    _orig_import = builtins.__import__
    if getattr(_orig_import, "_fireforge_guarded", False):
        return

    def _guarding_import(name, *args, **kwargs):
        _module = _orig_import(name, *args, **kwargs)
        try:
            _patch_loaded_monitor_modules()
        except Exception:  # noqa: BLE001
            pass
        return _module

    _guarding_import._fireforge_guarded = True
    builtins.__import__ = _guarding_import


try:
    _guard_psutil()
    _patch_loaded_monitor_modules()
    _install_import_hook()
except Exception:  # noqa: BLE001
    pass
`;

/** Result of installing the mach resource guard before a dispatch. */
export interface MachResourceGuardInstallation {
  /**
   * Env overlay for the mach subprocess: the PYTHONPATH sitecustomize
   * fallback that covers the pre-venv bootstrap phase. Merged over
   * `process.env` by the exec layer.
   */
  env: Record<string, string>;
  /** site-packages directories the in-venv guard was written into. */
  sitePackagesDirs: string[];
}

/** Lists subdirectory names of `dir`, tolerating a missing directory. */
async function listSubdirs(dir: string): Promise<string[]> {
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name);
  } catch {
    return [];
  }
}

/**
 * Discovers `site-packages` directories of the mach virtualenvs under one
 * `_virtualenvs` root: `<root>/<venv>/lib/python<N.M>/site-packages`.
 */
async function discoverVenvSitePackages(virtualenvsDir: string): Promise<string[]> {
  const found: string[] = [];
  for (const venvName of await listSubdirs(virtualenvsDir)) {
    const libDir = join(virtualenvsDir, venvName, 'lib');
    for (const pythonName of await listSubdirs(libDir)) {
      if (!pythonName.startsWith('python')) continue;
      const sitePackages = join(libDir, pythonName, 'site-packages');
      if (await pathExists(sitePackages)) {
        found.push(sitePackages);
      }
    }
  }
  return found;
}

/**
 * Discovers every mach virtualenv site-packages dir relevant to an engine
 * checkout: the objdir venvs (under `<engineDir>/obj-&lt;x&gt;/_virtualenvs`)
 * and the mach state-dir venvs (under `$MOZBUILD_STATE_PATH` or
 * `~/.mozbuild`, in `srcdirs/&lt;hash&gt;/_virtualenvs`, where mach keeps the
 * `mach` command venv itself).
 */
async function discoverMachSitePackages(engineDir: string): Promise<string[]> {
  const found: string[] = [];

  for (const name of await listSubdirs(engineDir)) {
    if (!name.startsWith('obj-')) continue;
    found.push(...(await discoverVenvSitePackages(join(engineDir, name, '_virtualenvs'))));
  }

  const stateDir = process.env['MOZBUILD_STATE_PATH'] ?? join(homedir(), '.mozbuild');
  for (const srcdirName of await listSubdirs(join(stateDir, 'srcdirs'))) {
    found.push(
      ...(await discoverVenvSitePackages(join(stateDir, 'srcdirs', srcdirName, '_virtualenvs')))
    );
  }

  return found;
}

/**
 * Writes the PYTHONPATH `sitecustomize.py` fallback into a stable
 * FireForge-owned temp directory and returns that directory. Idempotent —
 * overwriting each call keeps it in sync with this source across upgrades.
 */
async function ensureSitecustomizeFallback(): Promise<string> {
  const dir = join(tmpdir(), RESOURCE_SHIM_DIRNAME);
  await ensureDir(dir);
  await writeText(join(dir, 'sitecustomize.py'), GUARD_PYTHON_SOURCE);
  return dir;
}

/**
 * Builds the `env` overlay (merged over `process.env` by the exec layer)
 * that prepends the fallback shim directory to `PYTHONPATH` without
 * clobbering an existing `PYTHONPATH`.
 */
function machResourceShimEnv(
  shimDir: string,
  baseEnv: NodeJS.ProcessEnv = process.env
): Record<string, string> {
  const existing = baseEnv['PYTHONPATH'];
  return { PYTHONPATH: existing ? `${shimDir}${delimiter}${existing}` : shimDir };
}

/**
 * Installs the resource-monitor degrade guard for a mach dispatch:
 * `fireforge_mach_guard.pth` + `fireforge_mach_guard.py` into every
 * discovered mach virtualenv site-packages (survives mach's venv re-exec),
 * plus the PYTHONPATH sitecustomize fallback for the pre-venv bootstrap
 * phase. Idempotent and re-run before EVERY protected dispatch (including
 * each retry) so a venv created by a crashed first attempt is guarded on
 * the next one instead of re-dying on the same wedged state.
 */
export async function installMachResourceGuard(
  engineDir: string
): Promise<MachResourceGuardInstallation> {
  const sitePackagesDirs = await discoverMachSitePackages(engineDir);
  for (const sitePackages of sitePackagesDirs) {
    try {
      await writeText(join(sitePackages, `${GUARD_MODULE_NAME}.py`), GUARD_PYTHON_SOURCE);
      await writeText(
        join(sitePackages, `${GUARD_MODULE_NAME}.pth`),
        `import ${GUARD_MODULE_NAME}\n`
      );
    } catch (error: unknown) {
      // A read-only or vanished venv must not block the dispatch; the
      // PYTHONPATH fallback still applies and other venvs may have taken
      // the guard.
      verbose(
        `Could not install mach resource guard into ${sitePackages}: ${toError(error).message}`
      );
    }
  }

  const env = machResourceShimEnv(await ensureSitecustomizeFallback());
  return { env, sitePackagesDirs };
}
